# Generated by Django 6.0.3 on 2026-04-15 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0002_delete_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='user',
        ),
    ]
