# Generated by Django 6.0.1 on 2026-04-15 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0005_booking_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='user',
        ),
    ]
