# Generated by Django 6.0.1 on 2026-04-15 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0006_remove_booking_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('cod', 'Cash on Delivery'), ('esewa', 'eSewa')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending Payment'), ('paid', 'Paid')], default='pending', max_length=20),
        ),
    ]
